version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install jest
          command: npm i jest

workflows:
  version: 2
  test:
    jobs: 
      - build